# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Virtuágora - Plataforma Web de Participación ciudadana
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Plataforma web de participación ciudadana, diseñado para complementar el proceso democrático de cualquier ámbito afín. Software libre, abierto y gratuito.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://virtuagora.org" # the base hostname & protocol for your site
github_username:  virtuagora
repository: virtuagora/virtuagora.github.io

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"

# Paginator
paginate: 4
paginate_path: "/blog/page:num/"


# Build settings
markdown: kramdown

# Sass configurations
sass:
    style: compressed

gems:
  - jekyll-seo-tag
